### ISSUE TITLE
Can't use ssh key with passphrase

### ISSUE THREAD

**Issue by renich** [spider-gazelle/ssh2.cr#2]
I am trying something like:

```crystal
# TODO: Write documentation for `Getver`
require "ssh2"

module Getver
  VERSION = "0.1.0"

  SSH2::Session.open("some.host.example.tld", 1234) do |session|
    session.login_with_pubkey( "renich", "/home/user/.ssh/mykey", "/home/user/.ssh/mykey.pub", "redacted" )
    channel = session.open_session

    # request the terminal has echo mode off
    channel.request_pty("vt100", [{SSH2::TerminalMode::ECHO, 0u32}])
    channel.shell

    # Send commands
    spawn {
      list = ["ls\n", "ps aux\n", "uptime\n"]
      loop do
        channel.write(list.sample(1)[0].to_slice)
        sleep 3
      end
    }

    # Receive responses
    raw_data = Bytes.new(2048)
    loop do
      bytes_read = channel.read(raw_data)
      puts String.new(raw_data[0, bytes_read])
    end
  end
end
```

I am getting this error:

```
Unhandled exception: ERR -19: Callback returned error (SSH2::SessionError)
  from lib/ssh2/src/ssh2.cr:186:10 in 'check_error'
  from lib/ssh2/src/session.cr:440:5 in 'check_error'
  from lib/ssh2/src/session.cr:57:9 in 'login_with_pubkey'
  from src/getver.cr:8:5 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

Also, tried using `login_with_agent` but I can't provide a passphrase.

**Comment by stakach** [comment]
That is annoying. Personally I wouldn't use that function and I might remove it from the library as the file read in libssh2 will block the crystal event loop.

I'd use the `login_with_data` function - after reading the files off the disk.
I should build a helper function to replace the `login_with_pubkey` that does that in the background...

That said, I would try: `session.login_with_pubkey( "renich", "/home/user/.ssh/mykey", "/home/user/.ssh/mykey.pub", "redacted".to_slice.to_unsafe )` (I'll improve this too)

Otherwise given the passphrase code is part of libssh2 I'm not sure what I can do but recommend updating to the latest version of libssh2 (which is annoyingly hard to do with current packages available on most linux distros)

I would also retry the connection process on failure, I've noticed that I often get failures on the first connection attempt with libssh2 on tests I run in my projects even though they should succeed the first time.
You can see some of my code here: https://github.com/aca-labs/crystal-engine-driver/blob/master/src/engine-driver/transport/ssh.cr#L62

I put this down to the old version on the linux distros I am using and I use: https://github.com/Sija/retriable.cr to solve the problem.

**Comment by renich** [comment]
Thank you very much! I got it working. As a note, it works with RSA @ 8192 bit but it doesn't work with ED25519. Just a thing to note.

**Comment by stakach** [comment]
Sweet, thanks for the info, I'll add that to the readme.
Also let's leave this issue open until `login_with_pubkey` is upgraded to be non-blocking

**Comment by renich** [comment]
Right on. Thanks a lot!
